import Link from 'next/link';
export default function Home(){return <main>
<section className="hero"><div className="hero-img"/><div className="hero-content"><span className="eyebrow">HEY, I'M ADITYA</span><h1>Life is too short to live someone else's version of it.</h1><p>I'm still figuring life out. These are the places, people and moments helping me along the way.</p><div className="actions"><Link className="btn primary" href="/journeys">Explore my journeys →</Link><Link className="btn" href="/about">About Aditya →</Link></div></div></section>
<section className="section philosophy"><div><span className="eyebrow">WHY I TRAVEL</span><h2>Before you build your life, take the time to discover what you want it to be.</h2></div><div><p className="philosophy-copy">I don't think life should become a race for money, possessions and a version of success someone else chose for us.</p><div className="principles"><div className="principle"><strong>FREEDOM</strong><p>Find the courage to choose your own direction.</p></div><div className="principle"><strong>EXPLORATION</strong><p>Go see places, cultures and perspectives beyond your routine.</p></div><div className="principle"><strong>PEOPLE</strong><p>Every stranger carries a story worth hearing.</p></div><div className="principle"><strong>GROWTH</strong><p>Your path can be slower and still be yours.</p></div></div></div></section>
<section className="section"><div className="section-head"><div><span className="eyebrow">THE ROAD SO FAR</span><h2>My Journeys</h2></div><Link className="btn" href="/journeys">All journeys →</Link></div><div className="journey-feature"><div className="journey-copy"><span className="eyebrow">FEATURED JOURNEY · MAHARASHTRA</span><h3>The road is always more than the destination.</h3><p>Real trips, people, photographs and reflections — told as they happened.</p><Link className="btn primary" href="/journeys">Explore journey →</Link></div></div></section>
<section className="section"><div className="section-head"><div><span className="eyebrow">FROM MY MIND</span><h2>Blog</h2></div><Link className="btn" href="/blog">All blogs →</Link></div><div className="cards">{['What the road teaches us','The life I want to build','Why strangers matter'].map((x,i)=><article className="card" key={x}><div className="visual"/><span className="eyebrow">THOUGHT {String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>Individual thoughts about freedom, people, travel and finding your own way.</p></article>)}</div></section>
<section className="section"><div className="section-head"><div><span className="eyebrow">PLACES I HAVEN'T SEEN YET</span><h2>Dream Destinations</h2></div><Link className="btn" href="/dream-destinations">Explore all →</Link></div><div className="destinations">{['Nepal','Japan','Iceland','Bhutan','Norway'].map(x=><div className="destination" key={x}><div><span className="eyebrow">ONE DAY</span><h3>{x}</h3></div></div>)}</div></section>
<section className="section"><div className="encounter"><div><span className="eyebrow">PEOPLE I'VE MET ALONG THE WAY</span><h2>The conversations I never planned are often the ones I remember.</h2></div><div><p className="lead">Some encounters last twenty minutes. Some stay with you for years. When a person has a story worth sharing, it can live inside a Journey — and sometimes make its way here.</p><Link className="btn" href="/journeys">Meet the stories →</Link></div></div></section>
<section className="closing"><span className="eyebrow">STILL FIGURING IT OUT.</span><h2>The journey is still being written.</h2><p className="lead">Maybe you don't need all the answers before you start. Maybe you just need to take the first step toward a life that feels like yours.</p><div className="actions"><Link className="btn primary" href="/about">Meet Aditya →</Link><Link className="btn" href="/contact">Let's connect →</Link></div></section>
</main>}
